### ISSUE TITLE
Issues after uploading

### ISSUE THREAD

**Issue by kabe2007** [ItKindaWorks/ESPHelper#21]
Hello, 

Thanks for the library. I was using it with a Wemos D1 Mini, and had the following issue after OTA uploading: I got the message " [ERROR} No Answer" and did not get the message "Done uploading"...
And then got asked to upload again. 

Found a solution (I do not know if is ideal, but worked for me):
1) In ESPHelper.cpp, in the event handler ArduinoOTA.onEnd, start with a delay(500) - this gives time to send ok message back before killing wifi. So code would be:
....
ArduinoOTA.onEnd([]() { 
			delay(500);
			//on ota end we disconnect from wifi cleanly before restarting.
			WiFi.softAPdisconnect();
.....
2) Also need to give time to connect wifi before startup, if not will still ask to upload again. Change timeout from 2seg to 20 seg. Code would be (also in ESPHelper.cpp, a few lines down)
....
		while (((!client.connected() && _mqttSet) || WiFi.status() != WL_CONNECTED) && timeout < 2000 ) {	//max 20 sec before timeout
....
Hopefully this helps. Thank you for your great work. Looking forward to using the library with an ESP32 (still not arrived). 
Kabe

**Comment by ItKindaWorks** [comment]
Hi,

I will add in the code to onEnd to give a small delay. I assumed that the onEnd func was called after sending the a-ok message to Arduino but I could be wrong.

As for the connect part, I'm a little confused as to why that would matter as part of the upload process. I made it a small 2 sec routine because I felt that it would generally have no impact on the use of ESPHelper if it didn't connect right at startup especially if the user is running the loop function frequently in the Arduino loop (which will attempt to connect if it isn't currently). The reason for 2 seconds is to cut down on the amount of time that ESPHelper blocks other code from running at startup.

**Comment by RanielMarpuri** [comment]
hey i have a problem after the password.

it shows me this

Arduino: 1.8.5 (Windows 8.1), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Archiving built core (caching) in: C:\Users\Marlon\AppData\Local\Temp\arduino_cache_441534\core\core_esp8266_esp8266_nodemcuv2_CpuFrequency_80,FlashSize_4M1M,LwIPVariant_v2mss536,Debug_Disabled,DebugLevel_None____,FlashErase_none,UploadSpeed_115200_f7c9593c1643f82bc455f4b0b3a9ab6c.a
Sketch uses 373416 bytes (35%) of program storage space. Maximum is 1044464 bytes.
Global variables use 37164 bytes (45%) of dynamic memory, leaving 44756 bytes for local variables. Maximum is 81920 bytes.
java.io.IOException: Cannot run program "python.exe": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at processing.app.helpers.ProcessUtils.exec(ProcessUtils.java:26)
	at cc.arduino.packages.Uploader.executeUploadCommand(Uploader.java:129)
	at cc.arduino.packages.uploaders.GenericNetworkUploader.uploadUsingPreferences(GenericNetworkUploader.java:99)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:78)
	at processing.app.SketchController.upload(SketchController.java:713)
	at processing.app.SketchController.exportApplet(SketchController.java:686)
	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2168)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 8 more
An error occurred while uploading the sketch

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by ItKindaWorks** [comment]
To me that looks more like an issue with your Arduino installation/the upload tools.  The line 

> java.io.IOException: Cannot run program "python.exe": CreateProcess error=2, The system cannot find the file specified

makes me think that the issue might be that you dont have python installed (or installed correctly at least).

**Comment by RanielMarpuri** [comment]
Maybe reinstallin it might fix it ? Im on a windows 8.1
