### ISSUE TITLE
fatal error: ESPHelper.h: No such file or directory

### ISSUE THREAD

**Issue by zmi26** [ItKindaWorks/ESPHelper#28]
i compiled the code with #include "ESPHelper.h" . it state the error because of ESPHelper.h: No such file or directory. compilation terminated.
Error compiling. Help me please i have installed the Metro library, what else should be included?

**Comment by ItKindaWorks** [comment]
This is likely because your installation of ESPHelper wasnt put into the correct folder. Follow the library installation instructions found [here](https://www.arduino.cc/en/guide/libraries#toc5)

I'm going to close this topic but let me know if you are still having issues and I can try to help troubleshoot things.
