### ISSUE TITLE
Breaks with ArduinoJson 6.15.2

### ISSUE THREAD

**Issue by JosefGansinger** [ItKindaWorks/ESPHelper#36]
Can't compile scatch anymore.
Arduino update 6.15.2 breaks it

**Comment by gotenham** [comment]
Yes, i was having issues compiling the simple examples in this library, turns out it was related to the version of ArduinoJson i was using. I've rolled back one version at a time till it worked, the last version i found which is stable is 6.14.1, everything after that and EPSHelper will not compile for me

**Comment by ljcmps01** [comment]
Same here, I was trying to fix a bug on my room lights and it couldn't even compile the code, I'll try using an older version of ArduinoJson.

**Comment by ItKindaWorks** [comment]
This issue has been resolved in the latest update. ESPHelper should now work up through the latest version 6.17.0. Sorry about that issue sticking around so long!
