### ISSUE TITLE
Not longer compatible with lastest version of the board

### ISSUE THREAD

**Issue by ljcmps01** [ItKindaWorks/ESPHelper#37]
Was making some improvement to one of my home projects and while it compiles and upload just fine (with ArduinoJson.h at version 6.14, cause newer versions aren't compatible anymore) the ESP just keeps resetting itself every 15 seconds through hardware WDT.
It reaches till the end of the void setup() with no problems (connects to WiFi, enables OTA and sets up MQTT connection) and then after a few seconds it resets.
I replaced the ESPHelper with standard ESP8266, PubSubClient and Arduino OTA and everything works fine again
Doing some debugging I've found out that the issue belongs to ESPHelper::loop() method.

**Comment by ItKindaWorks** [comment]
Thanks for the info, I'm coming back to this project and trying to make some updates/fixes so I'll keep in mind that the loop method may need to minor tweaks. FYI the latest version now supports the ArduinoJSON 6.17.0 :) 

I know it has been a while since you posted this but if you have any logs from your troubles that may be helpful as I haven't run into the issues you're describing.
